### ISSUE TITLE
CSS Splitter has as typo in the Packagist name

### ISSUE THREAD

**Issue by cgsmith** [dlundgren/php-css-splitter#3]
This might be a moot issue but when trying to call `csssplitter/cssspliter` there is a missing S in the package name.

So `csssplitter/cssplitter` is the current name.

**Comment by dlundgren** [comment]
I renamed the package to dlundgren/css-splitter. Not ideal but the best way to actually fix the naming issue, this makes the css and splitter parts more visible.

Also updated the packages on packagist.
