### ISSUE TITLE
Great tool, but what if the css file is compressed? 

### ISSUE THREAD

**Issue by aolin480** [dlundgren/php-css-splitter#5]
Our problem is, we compress the css file, so it's not getting an accurate number of selectors. Is there anything I can do to count the actual CSS selectors in a compressed CSS file?

Thanks!

**Comment by dlundgren** [comment]
Compression as in gzip or stripped of whitespace?

**Comment by aolin480** [comment]
Yeah, just stripped of white space

**Comment by dlundgren** [comment]
I just tried putting Bootstrap 3.3.6's min.css through the splitter and it counted the selectors properly at 2511.

Can you send me the css that is causing the issues so I can look into this more?

**Comment by aolin480** [comment]
Here is an example compressed CSS file with no modifications. The entire css is pretty much on one line (and some others) --> https://gist.github.com/aolin480/7ffff2714e9366837296

**Comment by aolin480** [comment]
I even tried this site, but the number is off as well I think due to heavy compression--> http://snippet.bevey.com/css/selectorCount.php

**Comment by dlundgren** [comment]
Thanks for reporting this issue. It definitely made me go through and double check the other premises I had when I created this lib. However, the counts come out properly for me when I de-compress the CSS via PhpStorm and pass that through the Splitter, manually counting the selectors, and comparing against the compressed version against the CSS in the gist.

At first I thought it was related to the @ rules being processed incorrectly but according to others who have dealt with this issue it is only the rules in an @media block that actually count in the selector limitation [StackOverflow comment about this](http://stackoverflow.com/a/25089619/1281788).

If the counting problem continues with the selectors, please provide the following for me: specifically what you are expecting the count to be against the said CSS in the gist. If this continues to be a problem, and you can't share the full CSS that is causing issues publicly, please contact me directly (my email is in the composer.json).
